"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
#from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!l3!x0w-(f39+(@*a3a^8p@gf+o66e(@c#w1u13u*0=#-qpxbn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'user.apps.UserConfig',
    'order.apps.OrderConfig',
    'product.apps.ProductConfig',
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'mptt',
    'currencies',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'currencies.context_processors.currencies'
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en'


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
DEFAULT_CURRENCY = 'USD'
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False
USE_L10N = False


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')


# ...
SITE_ID = 1

####################################
##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'images/'
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
    },
}

###################################

#APPEND_SLASH=False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "My Admin Panel",  # Title for the admin panel
    "SITE_HEADER": "Admin Dashboard",  # Title at the top of the sidebar

    "SITE_LOGO": {
        "light": lambda request: static("images/logo-light.svg"),
        "dark": lambda request: static("images/logo-dark.svg"),
    },
    "SITE_SYMBOL": "home",  # Icon used in the admin panel
    "SHOW_HISTORY": True,  # Show history button
    "SHOW_VIEW_ON_SITE": True,  # Show "View on site" button
    "THEME": "light",  # Default theme for admin panel (light or dark)

    "SIDEBAR": {
        "show_search": False,  # Disable search in sidebar
        "show_all_applications": False,  # Disable all application listing
        "navigation": [
              {
                "title": _("Dashboard"),
                "icon": "dashboard",  # Icon for dashboard
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Icon for dashboard
                        "link": reverse_lazy("admin:index"),
                    },
                ]
            },
            # Authentication and Authorization section
           

            # Currencies section
            {
                "title": _("Currencies"),
                "icon": "attach_money",
                "items": [
                    {
                        "title": _("Currencies"),
                        "icon": "currency_exchange",
                        "link": reverse_lazy("admin:currencies_currency_changelist"),
                    },
                ]
            },

            # Home section
            {
                "title": _("Home"),
                "icon": "home",
                "items": [
                    {
                        "title": _("Contact messages"),
                        "icon": "message",
                        "link": reverse_lazy("admin:home_contactmessage_changelist"),
                    },
                    {
                        "title": _("Faqs"),
                        "icon": "help",
                        "link": reverse_lazy("admin:home_faq_changelist"),
                    },
                    {
                        "title": _("Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:home_setting_changelist"),
                    },
                ]
            },

            # Order section
            {
                "title": _("Order"),
                "icon": "receipt_long",
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:order_order_changelist"),
                    },
                    {
                        "title": _("Order products"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:order_orderproduct_changelist"),
                    },
                    {
                        "title": _("Shop carts"),
                        "icon": "shopping_basket",
                        "link": reverse_lazy("admin:order_shopcart_changelist"),
                    },
                ]
            },

            # Product section
            {
                "title": _("Product"),
                "icon": "storefront",
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:product_category_changelist"),
                    },
                    {
                        "title": _("Products"),
                        "icon": "production_quantity_limits",
                        "link": reverse_lazy("admin:product_product_changelist"),
                    },
                    {
                        "title": _("Colors"),
                        "icon": "palette",
                        "link": reverse_lazy("admin:product_color_changelist"),
                    },
                    {
                        "title": _("Sizes"),
                        "icon": "straighten",
                        "link": reverse_lazy("admin:product_size_changelist"),
                    },
                    {
                        "title": _("Variants"),
                        "icon": "layers",
                        "link": reverse_lazy("admin:product_variants_changelist"),
                    },
                    {
                        "title": _("Images"),
                        "icon": "image",
                        "link": reverse_lazy("admin:product_images_changelist"),
                    },
                    {
                        "title": _("Comments"),
                        "icon": "comment",
                        "link": reverse_lazy("admin:product_comment_changelist"),
                    },
                ]
            },

            # User section
            {
                "title": _("User"),
                "icon": "people",
                "items": [
                    {
                        "title": _("User profiles"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:user_userprofile_changelist"),
                    },
                ]
            },
             {
                "title": _("Authentication and Authorization"),
                "icon": "lock",
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                ]
            },
        ],
    },

    # Define colors for light and dark themes
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "default-light": "75 85 99",
            "important-light": "17 24 39",
        },
        "primary": {
            "100": "243 232 255",
            "500": "168 85 247",  # Main color for buttons or highlights
            "900": "88 28 135",
        },
    },
}
